image:
  repository: "library/wordpress"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6"

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wp.k8s-11.sa

persistentVolumeClaim:
  storageSize: 10Gi

extraEnvs:
  - name: WORDPRESS_DB_HOST
    value: 192.168.202.26 
  - name: WORDPRESS_DB_NAME
    value: wordpressdb
  - name: WORDPRESS_DB_USER
    value: root
  - name: WORDPRESS_DB_PASSWORD
    value: root
  - name: WP_DEBUG_LOG
    value: root
